
name: Build

on: [push,pull_request]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'zulu'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
      - name: Create Secret File
        env:
          TEMP_FOLDER: /home/runner/work/gradle-slimjar-docker-plugin/gradle-slimjar-docker-plugin/plugin/
        run: |
          echo -n "${{ secrets.GRADLE_PROPERTIES }}" | base64 --decode > ~/.gradle/gradle.properties
          echo -n "${{ secrets.SIGNING_SECRET_KEY_RING_CONTENT }}" | base64 --decode > $TEMP_FOLDER/secring.gpg
      - name: Validate publishing Gradle Plugin
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build publishPlugins --validate-only

